# Generated by Django 4.2 on 2023-04-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_schedule', '0002_alter_dutyscheduler_duty_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyscheduler',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
