# Generated by Django 4.2 on 2023-04-05 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('men_count', models.IntegerField(default=4, help_text='How many servicemen required for duty')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('unavailable', models.BooleanField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty_schedule.unit')),
            ],
            options={
                'verbose_name': 'Serviceman',
                'verbose_name_plural': 'Servicemen',
            },
        ),
        migrations.CreateModel(
            name='DutyScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(default=datetime.date(2023, 4, 5))),
                ('servicemen', models.ManyToManyField(related_name='schedules', to='duty_schedule.serviceman')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty_schedule.unit')),
            ],
        ),
    ]
