# Generated by Django 4.2 on 2023-04-06 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyscheduler',
            options={'ordering': ['-duty_date']},
        ),
        migrations.AddField(
            model_name='serviceman',
            name='last_duty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dutyscheduler',
            name='duty_date',
            field=models.DateField(default=datetime.date(2023, 4, 6)),
        ),
    ]
