# Generated by Django 4.2 on 2023-04-07 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_schedule', '0002_alter_dutyscheduler_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyscheduler',
            name='duty_date',
            field=models.DateField(default=datetime.date(2023, 4, 7)),
        ),
    ]
