# Generated by Django 4.2 on 2023-04-11 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_schedule', '0003_alter_dutyscheduler_duty_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyscheduler',
            name='duty_date',
            field=models.DateField(default=datetime.date(2023, 4, 11)),
        ),
    ]
